Project setup and header
NduatiKagiri/my-portfolio pull request #1
Opened 2022-03-18 18:22 UTC by NduatiKagiri

In this branch I:
Setup the project
Setup Linters
Added gitignore file
Added README file
Added test file
Added HTML file
Added CSS file
Added image files

2022-03-18 22:09 UTC, topeogunleye requested changes
Hi @NduatiKagiri,

Good job so far! +1
There are some issues that you still need to work on to go to the next project but you are almost there!

Required Changes :recycle:




 

- [ ] Your page is not currently optimized well for the mobile version. Please fix the down scrollbar from your page. You can use [CSS Media Queries](https://www.w3schools.com/css/css3_mediaqueries.asp) if you want to make your site responsive.

https://user-images.githubusercontent.com/52934128/159090733-9690a8c4-86d2-44ad-bc2a-16c986670baf.mp4

[](https://user-images.githubusercontent.com/70483835/159016071-ad193df8-6ecc-4d99-9512-1e6167591712.png)Check the comments under the review for more suggestions. :arrow_down: 
To Highlights
:heavy_check_mark:  No linters error.
:heavy_check_mark: Github flow used properly.
:heavy_check_mark: Descriptive PR title & description.

Optional suggestions
Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

Cheers and Happy coding! :clap: :clap: :clap: 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.
https://user-images.githubusercontent.com/52934128/159083097-325d3d61-1d84-4856-a48d-3751c308444e.mp4

2022-03-18 22:09 UTC, topeogunleye commented on README.md
> +Run tests
- [ ] I suggest you kindly remove the tests section as there are no there tests in this project.

2022-03-19 14:18 UTC, phelian23 requested changes
Hi @NduatiKagiri, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-19 14:18 UTC, phelian23 commented on index.html
> +      </div>
- [ ] [Optional]  Kindly separate the Headline section from the toolbar section, the headline section should be wrapped in a `<section>` tag and outside of the <header> tag.
You should only use the <header> element to identify content that precedes the primary content of the web page and it often contains website branding, navigation elements, search forms, and similar content that is duplicated across all or most pages of a website.

Read more: https://html.com/tags/header/#ixzz7NkefLEt8

2022-03-19 14:18 UTC, phelian23 commented on style.css
> +  }
- [ ] Kindly make sure that your design matches the Figma template as much as possible (e.g., font, colors, images, tests, margins)
Your design
![Capture](https://user-images.githubusercontent.com/85095702/159124625-3212abbd-3c53-4551-b553-b2b2aed175cc.PNG)

Figma template
![figma](https://user-images.githubusercontent.com/85095702/159124645-2f595143-0acf-4fd0-8a43-010fb136ff62.PNG)

2022-03-19 14:18 UTC, phelian23 commented on style.css
> +}
- [ ] [Optional] Instead of using `display: flex;` multiple times, kindly create a class say
``` css
.flex {
  display: flex;
}
```
and use the class in the HTML element that needs it. This will help your code to follow the DRY rule.

2022-03-19 17:58 UTC, nicupop729 approved these changes
<h1>Status: Approved 🥇 ✔</h1>
Hi @NduatiKagiri,

### Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
## Congratulations! 🎉 


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

<img src="https://media.giphy.com/media/aNqEFrYVnsS52/giphy.gif" width="100%">

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-19 18:02 UTC, merged