Design work and about sections
NduatiKagiri/my-portfolio pull request #2
Opened 2022-03-19 20:45 UTC by NduatiKagiri

In this branch I:
Added the work and about sections in HTML file
Added the work and about designs in css file
Added image files

2022-03-19 21:26 UTC, AnselemOdims requested changes
### Hi @NduatiKagiri, 
You have been doing a tremendous job so far :ok_hand:
There are some issues that you still need to work on to go to the next project but you are almost there!

## To Highlight 🎉
PR has a title and summary. :heavy_check_mark:
No linter errors :heavy_check_mark:

## Required Changes ♻️
- [ ] Please also check inline comments under the review

## Optional suggestions
_Comments with the [OPTIONAL] prefix are not a must to implement however, It's strongly recommended to work on them as they can make your code better._

## Happy coding!👏👏👏

#### Please leave any questions or comments in the PR if you have any doubts or unclarity! You can tag me using @AnselemOdims for a quicker response

**_Note: Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-03-19 21:26 UTC, AnselemOdims commented on index.html
> +              <p>Multi-Post Stories</p>
- [ ] Please make sure this and subsequent project title use a header tag `h2-h6` for semantic reasons

2022-03-19 21:26 UTC, AnselemOdims commented on index.html
> +                <div class="">
- [ ] [OPTIONAL] It is not good practice to have empty classes. Kindly remove it completely if it has no value

2022-03-19 21:26 UTC, AnselemOdims commented on index.html
> +              <h6>Languages</h6>
- [ ] Please kindly ensure that the technology categories ("Languages", "Frameworks" and "Skills") are in a `ul`, each of them in a `li`

2022-03-19 21:26 UTC, AnselemOdims commented on index.html
> +              <button class="flex" type="button" name="button">See Project</button>
- [ ] The list of technologies and the `button` are not properly aligned like that of the original design. Please kindly adjust to meet design requirements

### Your Design
![image](https://user-images.githubusercontent.com/43995830/159138539-61f7b59b-4144-4d38-925b-aec679c1196f.png)

### Original Design
![image](https://user-images.githubusercontent.com/43995830/159138549-aabad0e7-0b6a-481b-b0ac-f0353e16f605.png)

2022-03-19 21:26 UTC, AnselemOdims commented on index.html
> +                </div>
- [ ] Please ensure that your design for the project cards meet the original design guidelines(fonts, margins, padding, etc). At the moment, the buttons are not appearing on each card as specified in the original design

### Your Design
![image](https://user-images.githubusercontent.com/43995830/159138663-c250857d-40b8-4aaa-8645-ed08ab0e4cd8.png)

### Original Design
![image](https://user-images.githubusercontent.com/43995830/159138685-d7e2482c-2d12-4518-ad8a-20411c83fdc8.png)

2022-03-19 21:26 UTC, AnselemOdims commented on index.html
> +          </div>
- [ ] At the moment, the about section does not align with the original design guidelines in terms of spacing, fonts and colors. Please kindly compare your design with the original design and make necessary changes
- [ ] Also, the background image is not visible. Please kindly add the background image using the CSS `background-image` property

### Your Design 
![image](https://user-images.githubusercontent.com/43995830/159138761-d30d8e27-6f4d-49f1-8c7b-caf7e59c1d88.png)

### Original Design
![image](https://user-images.githubusercontent.com/43995830/159138776-a1b6e243-8fd3-4ea5-a217-dc17ecea867d.png)

2022-03-19 21:26 UTC, AnselemOdims commented on index.html
> +              </li>
- [ ] Please remove the empty whitespace to the right of the page that causes horizontal scroll.

![image](https://user-images.githubusercontent.com/43995830/159138927-4cb7d9fe-fd48-4bb9-aec9-e0206c8de3e9.png)

2022-03-23 20:03 UTC, thecodechaser approved these changes
## STATUS: APPROVED 🟢

## Hi @NduatiKagiri👋, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## To Highlight 🎉
- No linter errors. :heavy_check_mark:
- GitHub flow is followed. :heavy_check_mark:
- Professional README file. :heavy_check_mark:
- PR has a good title and summary. ✔️

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-24 08:34 UTC, merged