Contact form
NduatiKagiri/my-portfolio pull request #3
Opened 2022-03-30 10:39 UTC by NduatiKagiri

In this branch I:
Created the footer
Created the contact form
Styled the footer
Styled the contact form

2022-03-30 12:05 UTC, ShadyShawkat requested changes
## Hi @NduatiKagiri, 

Good job so far! 👍🏻 
There are some issues that you still need to work on to go to the next project but you are almost there!

![Image](https://media.giphy.com/media/UdaSUYClr92cjWpeVx/giphy.gif)

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-03-30 12:05 UTC, ShadyShawkat commented on index.html
> +    </footer>
- [ ] Please remove the extra space on the right of the design to match the Figma design.

| Your design | Figma design |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/62290545/160829243-c4eb72aa-0be0-4e27-9bde-0c912e1c4cca.png) | ![image](https://user-images.githubusercontent.com/62290545/160829437-f1891cc3-807a-451a-bcec-a00a05fa6bda.png) |

- This is likely caused by elements taking more space/width than they should take, and it's also caused by using fixed widths on containers which is not recommended. (See images below)

![image](https://user-images.githubusercontent.com/62290545/160829882-7d0b0ff3-ba99-4fd2-8046-0fddc91a6b9c.png)
![image](https://user-images.githubusercontent.com/62290545/160830004-88df7d7e-0cd2-4b4b-8b11-b7b16d2cf3e4.png)
![image](https://user-images.githubusercontent.com/62290545/160830095-7c8b6fbc-7ecc-4c0f-9490-f595de5f30b8.png)

2022-03-30 12:05 UTC, ShadyShawkat commented on index.html
> +        </div>
- [ ] While this is working for the design, it's not practical at all since these should be clickable links for your social profiles. Please replace this image with a list of `a` tags containing the social images.

2022-04-01 09:33 UTC, prolajumokeoni approved these changes
Hi @NduatiKagiri 
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
_Check comments under review_
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-01 09:33 UTC, prolajumokeoni commented on style.css
> +@media screen and (max-width: 768px) {
## OPTIONAL 
- [ ] Kindly use min width instead of max width, using min width will account for other screen sizes larger than 768px, currently the header and footer look different from any screen size above 768px
- Here is a video ⬇️ 

https://user-images.githubusercontent.com/69638013/161235126-190e784f-f45d-4fdf-82b8-98d671bb1a54.mp4

2022-04-01 09:33 UTC, prolajumokeoni commented on style.css
> +@media screen and (max-width: 763px) {
## OPTIONAL 
- [ ] Kindly use min width instead of max width, using min width will account for other screen sizes larger than 763px, currently the header and footer look different from any screen size above 763px
- Here is a video ⬇️ 

https://user-images.githubusercontent.com/69638013/161235126-190e784f-f45d-4fdf-82b8-98d671bb1a54.mp4

2022-04-01 09:33 UTC, prolajumokeoni commented on index.html
> +      </div>
### OPTIONAL
- [ ] Kindly wrap footer icons in ul tag and not div, and wrap each of the the anchor tags and images in an li tag 
 ```suggestion
 <ul>
         <li><a href="#"><img src="assets/GithubIcon.png" alt=""></a></li>
          <li><a href="#"><img src="assets/GithubIcon.png" alt=""></a></li>
          <li><a href="#"><img src="assets/GithubIcon.png" alt=""></a></li>
          <li><a href="#"><img src="assets/GithubIcon.png" alt=""></a></li>
          <li><a href="#"><img src="assets/GithubIcon.png" alt=""></a></li>
  </ul>
```

2022-04-01 10:36 UTC, bizip approved these changes
## Hi @NduatiKagiri, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![Image](https://media.giphy.com/media/qlrBlSDevEdFeW5JwV/giphy.gif)

## To Highlight
- Descriptive commit messages ✔️ 
- Fixed changes requested by the first reviewer ✔️ 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @bizip in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-04-01 10:45 UTC, merged